#!/usr/bin/env python

import datetime
import sys
import tempfile
import shutil

from tsclient.core import *
from tsclient.options import *

base_tmp = tempfile.mkdtemp()

def do_exit():
    shutil.rmtree(base_tmp)
    raise SystemExit

if __name__ == '__main__':
    
    try:
        fl = FileList(options.path, options.bootleg)
        lists = fl.get_temp_lists(base_tmp)
    except ImproperMP3Error, e:
        # show any show stopper errors, such as finding a file
        # named *.mp3 but its not an mp3
        print bright_red(e)
        do_exit()
    
    if not options.silent and fl.warnings:
        # show things like skipped .m3u files and crap
        print blue("\n".join(fl.warnings))
    
    if options.artist:
        set_tags(lists['mp3s'], 'artist', options.artist)
        
    if options.album:
        set_tags(lists['mp3s'], 'album', options.album)
        
    if options.date:
        set_tags(lists['mp3s'], 'date', options.date)
            
    if options.meta:
        set_tags(lists['mp3s'], 'comment', options.meta, append=True)
    
    try:
        result = validate_mp3s(lists['mp3s'])
    except ImproperMP3Error, e:
        print bright_red("MP3 tags did not validate: %s" % e)
        do_exit()
        
    artist = result['artist']
    album = result['album']
    preset = result['preset']
    date = result['date']
    
    tmp = tempfile.NamedTemporaryFile()
    zf = ZipFile(tmp, lists['mp3s'], lists['others'])
    
    if not options.silent:
        print zf.show_contents()
        size = tmp.tell()
        mb = size / 1048576.0
        print "------\nArchive Size: {0} bytes ({1:.2f} MB)".format(size, mb)
    
    ###########
    ###########
    
    if (not options.skip_verify and
        not options.just_archive and
        not options.silent):
        answer = raw_input("Does the above look all right? [y]/n?")
        if answer != '' and answer.upper() != 'Y':
            do_exit()
        
    if options.just_archive or options.leave_archive:
        tmp.seek(0)
        f = open('archive.zip', 'w')
        f.writelines(tmp.readlines())
        tmp.seek(0)
        if options.just_archive:
            do_exit()
        
    #####
    
    if not options.silent:
        print "Checking if this album is a dupe...",
        sys.stdout.flush()

    dupe, client_reject, latest_client, password_match =\
        pre_upload(artist, album, options.password, options.url)
    exit = False
    
    if password_match is None:
        print "Hrm"
        print bright_red("Some error occured, Try again later. (Server down maybe?)")
        exit = True
    
    if password_match == "No":
        print "Hrm"
        print bright_red("Wrong Password")
        do_exit()
    
    if client_reject == "Yes":
        print "Hrm"
        print bright_red("Upload will be rejected because your client is too old, please update")
        do_exit()
    
    if dupe == "Yes":
        print "Uh-oh"
        print bright_red("Album already exists in The System. This is a dupe")
        exit = True
    else:
        print "OK, not a dupe"
        
    if latest_client != "Latest":
        print "This is not the latest version of this sctipt, the latest vesion is:",
        print bright_green(latest_client) 
    
    if exit:
        do_exit()
    
    ##### send the file off to the server!
    
    data = dict(artist=artist, album=album, meta=options.meta,
                profile=preset, date=date, password=options.password)
    
    if not options.silent:
        print size, "bytes being sent to server...(ctrl+z to stop)"
    
    before = datetime.datetime.now()
    result = send_request(tmp, data, options.url, interface="Command Line")
    after = datetime.datetime.now()
    
    print result
    
    if not options.silent:
        duration = after - before
        speed = "{0:.2f} KB/sec".format((size / 1024.0) / duration.seconds)
        print "Total Time:", duration, speed
        
    
